// Writes src/db/schema-version.ts from drizzle/meta/_journal.json (run by `pnpm db:generate`).
// The backup file carries this tag so a restore can refuse a dump made by a NEWER schema (§11.4).
import { readFileSync, writeFileSync } from 'node:fs'
const journal = JSON.parse(readFileSync(new URL('../drizzle/meta/_journal.json', import.meta.url), 'utf8'))
const tag = journal.entries[journal.entries.length - 1].tag
writeFileSync(new URL('../src/db/schema-version.ts', import.meta.url), `// Generated by scripts/schema-version.mjs — do not edit.\nexport const SCHEMA_VERSION = '${tag}'\n`)
console.log('schema version', tag)
